// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: hoge/v1/hoge.proto

package hogev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetHoge
type HogeGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HogeGetRequest) Reset() {
	*x = HogeGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoge_v1_hoge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HogeGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HogeGetRequest) ProtoMessage() {}

func (x *HogeGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_v1_hoge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HogeGetRequest.ProtoReflect.Descriptor instead.
func (*HogeGetRequest) Descriptor() ([]byte, []int) {
	return file_hoge_v1_hoge_proto_rawDescGZIP(), []int{0}
}

func (x *HogeGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HogeGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hoge *Hoge `protobuf:"bytes,1,opt,name=hoge,proto3,oneof" json:"hoge,omitempty"`
}

func (x *HogeGetResponse) Reset() {
	*x = HogeGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoge_v1_hoge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HogeGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HogeGetResponse) ProtoMessage() {}

func (x *HogeGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_v1_hoge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HogeGetResponse.ProtoReflect.Descriptor instead.
func (*HogeGetResponse) Descriptor() ([]byte, []int) {
	return file_hoge_v1_hoge_proto_rawDescGZIP(), []int{1}
}

func (x *HogeGetResponse) GetHoge() *Hoge {
	if x != nil {
		return x.Hoge
	}
	return nil
}

// CreateHoge
type HogeCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hoge *Hoge `protobuf:"bytes,1,opt,name=hoge,proto3" json:"hoge,omitempty"`
}

func (x *HogeCreateRequest) Reset() {
	*x = HogeCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoge_v1_hoge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HogeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HogeCreateRequest) ProtoMessage() {}

func (x *HogeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_v1_hoge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HogeCreateRequest.ProtoReflect.Descriptor instead.
func (*HogeCreateRequest) Descriptor() ([]byte, []int) {
	return file_hoge_v1_hoge_proto_rawDescGZIP(), []int{2}
}

func (x *HogeCreateRequest) GetHoge() *Hoge {
	if x != nil {
		return x.Hoge
	}
	return nil
}

type HogeCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hoge *Hoge `protobuf:"bytes,1,opt,name=hoge,proto3" json:"hoge,omitempty"`
}

func (x *HogeCreateResponse) Reset() {
	*x = HogeCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoge_v1_hoge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HogeCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HogeCreateResponse) ProtoMessage() {}

func (x *HogeCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_v1_hoge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HogeCreateResponse.ProtoReflect.Descriptor instead.
func (*HogeCreateResponse) Descriptor() ([]byte, []int) {
	return file_hoge_v1_hoge_proto_rawDescGZIP(), []int{3}
}

func (x *HogeCreateResponse) GetHoge() *Hoge {
	if x != nil {
		return x.Hoge
	}
	return nil
}

type Hoge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fuga *Fuga `protobuf:"bytes,1,opt,name=fuga,proto3" json:"fuga,omitempty"`
}

func (x *Hoge) Reset() {
	*x = Hoge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoge_v1_hoge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hoge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hoge) ProtoMessage() {}

func (x *Hoge) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_v1_hoge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hoge.ProtoReflect.Descriptor instead.
func (*Hoge) Descriptor() ([]byte, []int) {
	return file_hoge_v1_hoge_proto_rawDescGZIP(), []int{4}
}

func (x *Hoge) GetFuga() *Fuga {
	if x != nil {
		return x.Fuga
	}
	return nil
}

type Fuga struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Piyo string `protobuf:"bytes,1,opt,name=piyo,proto3" json:"piyo,omitempty"`
}

func (x *Fuga) Reset() {
	*x = Fuga{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoge_v1_hoge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fuga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fuga) ProtoMessage() {}

func (x *Fuga) ProtoReflect() protoreflect.Message {
	mi := &file_hoge_v1_hoge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fuga.ProtoReflect.Descriptor instead.
func (*Fuga) Descriptor() ([]byte, []int) {
	return file_hoge_v1_hoge_proto_rawDescGZIP(), []int{5}
}

func (x *Fuga) GetPiyo() string {
	if x != nil {
		return x.Piyo
	}
	return ""
}

var File_hoge_v1_hoge_proto protoreflect.FileDescriptor

var file_hoge_v1_hoge_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x6f, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x20, 0x0a,
	0x0e, 0x48, 0x6f, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x42, 0x0a, 0x0f, 0x48, 0x6f, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68,
	0x6f, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x11, 0x48, 0x6f, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x68, 0x6f, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x6f, 0x67, 0x65, 0x52, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x12, 0x48,
	0x6f, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x04, 0x68, 0x6f, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x67, 0x65, 0x52, 0x04,
	0x68, 0x6f, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x04, 0x48, 0x6f, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x04,
	0x66, 0x75, 0x67, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x68, 0x6f, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x75, 0x67, 0x61, 0x52, 0x04, 0x66, 0x75, 0x67, 0x61, 0x22,
	0x1a, 0x0a, 0x04, 0x46, 0x75, 0x67, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x79, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x79, 0x6f, 0x32, 0x96, 0x01, 0x0a, 0x0b,
	0x48, 0x6f, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x48, 0x6f, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x6f, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x67, 0x65, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x68, 0x6f, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x68, 0x6f, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x6f, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2d,
	0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x6f, 0x67, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x68, 0x6f, 0x67, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hoge_v1_hoge_proto_rawDescOnce sync.Once
	file_hoge_v1_hoge_proto_rawDescData = file_hoge_v1_hoge_proto_rawDesc
)

func file_hoge_v1_hoge_proto_rawDescGZIP() []byte {
	file_hoge_v1_hoge_proto_rawDescOnce.Do(func() {
		file_hoge_v1_hoge_proto_rawDescData = protoimpl.X.CompressGZIP(file_hoge_v1_hoge_proto_rawDescData)
	})
	return file_hoge_v1_hoge_proto_rawDescData
}

var file_hoge_v1_hoge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hoge_v1_hoge_proto_goTypes = []interface{}{
	(*HogeGetRequest)(nil),     // 0: hoge.v1.HogeGetRequest
	(*HogeGetResponse)(nil),    // 1: hoge.v1.HogeGetResponse
	(*HogeCreateRequest)(nil),  // 2: hoge.v1.HogeCreateRequest
	(*HogeCreateResponse)(nil), // 3: hoge.v1.HogeCreateResponse
	(*Hoge)(nil),               // 4: hoge.v1.Hoge
	(*Fuga)(nil),               // 5: hoge.v1.Fuga
}
var file_hoge_v1_hoge_proto_depIdxs = []int32{
	4, // 0: hoge.v1.HogeGetResponse.hoge:type_name -> hoge.v1.Hoge
	4, // 1: hoge.v1.HogeCreateRequest.hoge:type_name -> hoge.v1.Hoge
	4, // 2: hoge.v1.HogeCreateResponse.hoge:type_name -> hoge.v1.Hoge
	5, // 3: hoge.v1.Hoge.fuga:type_name -> hoge.v1.Fuga
	0, // 4: hoge.v1.HogeService.GetHoge:input_type -> hoge.v1.HogeGetRequest
	2, // 5: hoge.v1.HogeService.CreateHoge:input_type -> hoge.v1.HogeCreateRequest
	1, // 6: hoge.v1.HogeService.GetHoge:output_type -> hoge.v1.HogeGetResponse
	3, // 7: hoge.v1.HogeService.CreateHoge:output_type -> hoge.v1.HogeCreateResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hoge_v1_hoge_proto_init() }
func file_hoge_v1_hoge_proto_init() {
	if File_hoge_v1_hoge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hoge_v1_hoge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HogeGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoge_v1_hoge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HogeGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoge_v1_hoge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HogeCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoge_v1_hoge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HogeCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoge_v1_hoge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hoge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoge_v1_hoge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fuga); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hoge_v1_hoge_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hoge_v1_hoge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hoge_v1_hoge_proto_goTypes,
		DependencyIndexes: file_hoge_v1_hoge_proto_depIdxs,
		MessageInfos:      file_hoge_v1_hoge_proto_msgTypes,
	}.Build()
	File_hoge_v1_hoge_proto = out.File
	file_hoge_v1_hoge_proto_rawDesc = nil
	file_hoge_v1_hoge_proto_goTypes = nil
	file_hoge_v1_hoge_proto_depIdxs = nil
}
