// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts"
// @generated from file hoge/v1/hoge.proto (package hoge.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HogeCreateRequest, HogeCreateResponse, HogeGetRequest, HogeGetResponse } from "./hoge_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service hoge.v1.HogeService
 */
export const HogeService = {
  typeName: "hoge.v1.HogeService",
  methods: {
    /**
     * @generated from rpc hoge.v1.HogeService.GetHoge
     */
    getHoge: {
      name: "GetHoge",
      I: HogeGetRequest,
      O: HogeGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc hoge.v1.HogeService.CreateHoge
     */
    createHoge: {
      name: "CreateHoge",
      I: HogeCreateRequest,
      O: HogeCreateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

